services:

  notebook:
    image: "quay.io/jupyter/scipy-notebook:latest"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work/bd2
    user: root
    environment:
      - GRANT_SUDO=yes
      - DB_HOSTNAME=redis
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
