version: '2'
services:
  notebook:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    user: root
    environment:
      - GRANT_SUDO=yes
    command: start-notebook.sh --ServerApp.token=''
    volumes:
      - .:/home/jovyan/bd2
